### ISSUE TITLE
Browser hashes & queries getting lost in server (universal, server-side) example

### ISSUE THREAD

**Issue by glennreyes** [reactjs/react-router-redux#365]
In the [server (universal) example](https://github.com/reactjs/react-router-redux/tree/master/examples/server), when I try to access ```http://localhost:8080/#foo``` via browser, the hash kind of disappears and the url transitions to ```http://localhost:8080/```.

I found out that the hash and query properties in ```routing``` in the initial state (which is globally accessible at ```window.__initialState__```) are empty strings.

When I remove the ```routing``` property on the client, the hashes and queries stay as intended, but I don't think it is a really good way to solve it.

What is the smartest way to handle this problem?

**Comment by timdorr** [comment]
Hashes aren't communicated to the server. But it seems like we're converting the URL to have a `hash` of empty string instead of null/undefined. Not sure if this is a bug here or in `history`, but it definitely is the cause of the problem.

**Comment by jonjaques** [comment]
I'm having the same issue with `browserHistory`. As @glennreyes said, I was able to work around it by [discarding](https://github.com/3five/protium/blob/master/src/store.js#L44) the routing state sent down by the server, but this may create issues with apps that manipulate router state via redux actions.

**Comment by glennreyes** [comment]
In which cases are routing information in the ```initialState``` needed?

**Comment by jonjaques** [comment]
I'm not sure frankly. This lib is new to me - but I imagine something along the lines of the following:

Lets say I have a `static needs(params, store): Promise` method on my view components. This is called on the server as part of the async universal rendering flow defined in the react-router docs. And in this fn, I'm doing an API call for a particular resource, which happens to 404. 

I feel like this is where I'd like to redirect to not-found component or some other page - and this would be the place to do it - all nicely encapsulated with redux.

**Comment by timdorr** [comment]
I'm like 99% sure this is a `history` thing which is fixed in 3.0 with some of the `state` and `key` changes. Once Router has support for 3.0, we should be good.

**Comment by diegohaz** [comment]
I'm still seeing this issue. All my querystrings are lost in the server (they don't get passed to initial state).

**Comment by kelchm** [comment]
I'm also dealing with this issue -- is there anything that can be done in the short term until support for `history` 3.0 is added to `react-router`?

**Comment by glennreyes** [comment]
@kelchm I had `react-router-redux` running and I could solve it by dealing with the state of `search` in `state.routing.locationBeforeTransition`. Hope this little detail helps you out a bit.

**Comment by glennreyes** [comment]
I actually fixed it somewhere on the server but this brought me to the root problem. 👍
